server:
  port: 8080

spring:
  application:
    name: property-management
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/property_management
    username: root
    password: wxq112211

logging:
  level:
    root: info
    com.smart.reader: debug